#!/bin/bash
echo "total 16-rwxr--r-- 1 root root 69 Oct  5 12:05 0-current_working_director-rwxr--r-- 1 root root 70 Oct  5 12:14 1-listit-rwxr--r-- 1 root root 28 Oct  5 12:23 2-bring_me_home-rw-r--r-- 1 root root 36 Oct  5 09:45 README.md"
